name: Model Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Install tox and dependencies
        run: |
          python -m pip install tox
      - name: Model training
        run: |
          tox -e train
      - name: "Reading the version file"
        id: package_version
        uses: juliangruber/read-file-action@v1
        with:
          path: "./titantic_classification/VERSION"
      - name: Release model
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ steps.package_version.outputs.content }}
          name: Release ${{ steps.package_version.outputs.content }}
          draft: false
          prerelease: false
          files: "./titantic_classification/trained_models/titanic_classification_outpyt_v${{steps.package_version.outputs.content}}.pkl"
